### ISSUE TITLE
Mejorando la carga de un sitio web, toda una gran aventura.

### ISSUE THREAD

**Issue by FiliSantillan** [javascriptmx/chelajs#116]
### Sumario

Muchas veces cuando se construye un sitio web, nunca tiene contemplado el performance, el número de peticiones que se están haciendo, las imágenes que se están cargando, peso de los archivos, etc. 
El objetivo de mi platica es tener en cuenta estos puntos y como resolverlos.

### Outline

1. Archivos y buenas prácticas
    - Compresión de código
    - Compresión de archivos
    - Critical CSS
    - Uso de CDN, basados en la ubicación
    - HTTP/2
    - Load
    - DOMContentLoaded
    - Webpack
    - Preload & Prefetch
2. Imágenes
    - Creando la imagen perfecta
    - Fuentes de iconos & base64
    - Compresión de imágenes
    - Tamaños y adaptaciones
    - LazyLoad
    - Procesamiento de imágenes 
3. Code splitting y offline
    - ¿Qué son?
    - ¿Cómo funcionan?
    - ¿En que nos ayudan?
    - Ejemplos
4. Herramientas
    - ¿Cómo saber en dónde mejorar?

Parece mucho, pero todo está preparado para hablarse en el lapso común de una charla (30 min).

```yaml
name: Fili Santillán
url: https://filisantillan.com/
pic: https://filisantillan.com/content/images/2018/07/fili-social.jpg
bio: "Frontend Developer, Speaker, Blogger, Geek, Lover of code" Frontend por Default | Technical Writer | Speaker | Geek 🎮
```
