### ISSUE TITLE
Stateful vs Stateless Components in ReactJs

### ISSUE THREAD

**Issue by ezegg** [javascriptmx/chelajs#123]
Summary 
In this presentation i will show and explain to you why is always better to create stateless components for your ReactJs project. 

Outline

1. What is stateful component?.
2. What is stateless component?.
3. Stateful vs stateless? again 🤔yes again.
4. Advantages and disadvantages but not is a rule to create always stateless components.
5. Final thoughts and conclusion.

```yaml
name: Ezequiel García
url: https://twitter.com/ezeezegg
pic:https://pbs.twimg.com/profile_images/953241026629652481/249OccUL.jpg
bio: "Hi, I'm Eze I love traveling, knowing the world and people. In my free time I'm Fullstack Developer in Follio, currently working with Reactjs 😍🙌"
```
