### ISSUE TITLE
Svelte: rediseñando la reactividad.

### ISSUE THREAD

**Issue by Ernjivi** [javascriptmx/chelajs#144]
### Sumario

Sevelte es un framework para crear aplicaciones web, que se enfoca en: Escribir menos código, no usar virtual DOM y ser realmente reactivo.

A diferencia de otros frameworks, a nivel compilación optimiza el código, así que lo que entrega es lo mínimo para la tarea requerida.

* No hay overhead como en React o Vue.
* El código va directo a vanilla JS.
* La reactividad se hace con vanilla JS.

Este regreso a hacer un vanilla JS, no es el JS que se hacía sin jQuery hace años, sino a través de un API que Svelte propone y que recoge todo lo bueno de dividir la interfaz en componentes (como React y Vue), pero sin el overhead que imponen dichos frameworks.

#### Presentación
* ¿Qué es Svele?
* ¿Cómo se compara Svelte a Frameworks con virtual DOM?
#### ¿Cómo iniciar un nuevo proyecto?
* Iniciando un proyecto svelte
#### Demo

```yaml
names: Ernesto Jiménez Villeñor & Leopoldo Caballero
url_ernesto: @Ernesto_JV
url_leopoldo: https://pitakill.net
pic_ernesto: "https://scontent-qro1-1.xx.fbcdn.net/v/t1.0-9/1504129_599443810199647_6888115707017590768_n.jpg?_nc_cat=105&_nc_ht=scontent-qro1-1.xx&oh=4b2c80340312f8d39e6e1451f83620a2&oe=5D8E02EB"
pic_leopoldo: "https://pitakill.net//img/profile.png"
bio_ernesto: "Soy un desarrollador autodicta, entuciasta del open source con una fascinación por las plantas carnívoras"
bio_leopoldo: "Leopoldo es un programador que actualmente hace Go, antes hizo JS, y antes Perl y antes PHP y antes bash. Y así es como inició en la programación. Actualmente hace herramientas para Devops en DigitalOnUs, pero en sus tiempos libres sigue explorando tecnologías como Sevelte, Wasm y Rust"
```
