### ISSUE TITLE
e-cuerpo 

### ISSUE THREAD

**Issue by voidrizoma** [javascriptmx/chelajs#145]
### Sumario
Fue en 1960 cuando a Clynes y Kline se les ocurrió hablar por primera vez del ciborg. Pero después de toda esa ciencia ficción, el estar rodeados de artefactos tecnológicos, ¿podremos hablar de la tecnología como una extensión del cuerpo?

### Outline

1. Contexto histórico del ciborg de Clynes y Kline
2. Un poco de antropología del cuerpo
- ¿se tiene o se es un cuerpo?
- El cuerpo como punto de partida de la experiencia.
- Del dualismo cartesiano (mente/cuerpo) a la fenomenología de Varela y la sociosemiótica de Scolari.

```yaml
name: Karen Molina
url: https://twitter.com/voidrizoma
pic:https://github.com/lawrayette/Karen-Molina/blob/master/src/assets/13443088_300875960244853_225541137525448957_o.jpg
bio: "Antropóloga Social por formación, actualmente en el camino de JS. Todo comenzó en un FLISoL"
```
