### ISSUE TITLE
Arte generativo y código creativo.

### ISSUE THREAD

**Issue by MitziYolotzin** [javascriptmx/chelajs#146]
### Sumario

Arte generativo y código creativo.
Conexiones entre código fuente y creatividad. 

### Outline

1. Presentación. 5 min.
  - Primeros acercamientos con el código.
  - Influencias e inspiración creativa.
2. Arte Generativo. 10 min.
  - Intersecciones: creatividad y programación.
  - Arte y Live Coding. 
  - Procesos en la creación en vivo a través del código.
 3. Recomendaciones para explorar y conocer. 5 min.
 - Nuevas tecnologías, Open Source, DIY.

```yaml
name: Mitzi Olvera
url: https://visuellcodeart.tumblr.com/
pic: https://ibb.co/ck8cy57
bio: Arte, código, ciencia, cultura. Front End Developer. Laboratorian. Diseño y Comunicación Visual.
```
