### ISSUE TITLE
Automatizando tareas creando nuestro propio CLI 

### ISSUE THREAD

**Issue by lzamudio** [javascriptmx/chelajs#147]
### Sumario

La automatización de procesos o tareas es un punto clave para aumentar nuestra productividad como desarrolladores lo que nos lleva a la busqueda de herramientas o frameworks para cumplir con dicho objetivo, pero ¿cuántas veces no hemos dicho? "Estaría genial si angular (por ejemplo) tuviera un comando para que me genere ....". 

El objetivo de esta charla es mostrarles como programar nuestra propia linea de comandos utilizando javascript y como compartirla con nuestro equipo de trabajo.

### Outline

1. ¿Qué es un CLI?
2. Cómo y por qué generé un CLI para mi equipo
  - Necesidad 
  - Cómo use `@nestjs/cli`, `@angular-devkit/schematics-cli` y `@angular-devkit/schematics`
3. Generando nuestro primer CLI con js
  - Creación de proyecto
  - Dependencias
  - Definición de comandos y opciones
  - Prompt 
  - Uso
  - Publicación

```yaml
name: Luis Zamudio
url: https://twitter.com/luis_zamudioc
pic: https://pbs.twimg.com/profile_images/344513261583320613/500e71b441202892102232327d8ec18a_400x400.jpeg
bio: "Encuentra lo que amas y deja que te mate"
```
