### ISSUE TITLE
Lenguaje Go en Arquitecturas dirigidas por eventos (EDA)

### ISSUE THREAD

**Issue by briferz** [javascriptmx/chelajs#148]
## Sumario
Las arquitecturas dirigidas por eventos estan basadas en módulos que traban juntos asemejandose a una coreografía: cada componente sabe qué hacer en el momento que un evento de su interés es emitido. El lenguaje Go y su concurrencia nativa permiten aprovechar de manera sencilla las posibilidades que estas arquitecturas tienen para ofrecer.

## Outline

1. Qué es una arquitectura dirigida por eventos
2. El caso de la UCM de CFE
- Stack empleado
- Arquitectura general
3. Uso de go-routines en la UCM
- WebSockets
- Proceso de guardado de valores históricos
4. Conclusiones

```yaml
name: Luis M. Brito
url: https://twitter.com/micheltekf
pic: https://pbs.twimg.com/profile_images/767165234293248001/lnCZueL3_400x400.jpg
bio: "Improvement is the only option"
```
