### ISSUE TITLE
Introducción al Arte Generativo

### ISSUE THREAD

**Issue by davidomarf** [javascriptmx/chelajs#150]
### Sumario

Guía breve para comenzar a producir arte generativo.
Fuerte enfoque en arte algorítmico visual. 

### Outline

1. ¿Qué es el arte, lo generativo, y el arte generativo?
    - Breve historia del arte generativo
    - Breve descripción de los tipos de arte generativo: imagen, música, literatura, arquitectura. 
1. ¿Qué necesito entender antes de empezar?
    - Representación
        - Sistemas coordenados en imágenes
    - Generación
        - Exploración de patrones comunes en el diseño de algoritmos generativos
        - Algunos principios de diseño
1. Adoptar o crear un _framework_
    - Mi _framework_ (JavaScript + P5.js)
    - Otros _frameworks_ populares
1. Muestras rápidas de código previamente preparado.
    - Ejemplificar los principios expuestos.
1. Consejos para comenzar
1. Recursos para obtener inspiración

```yaml
name: David Omar Flores Chávez
url: https://gen.davidomar.com/
pic: https://www.gravatar.com/avatar/46fb426e3869dfecf544cb47bd5bce25?s=400
bio: "Desarrollador front-end con gusto por la visualización de datos"
```
