### ISSUE TITLE
“Haga en directo!” con ObservableHQ, una platforma gratis por el creador de D3.js

### ISSUE THREAD

**Issue by pcarleton** [javascriptmx/chelajs#151]
## Sumario

ObservableHQ es un cuaderno de Javascript que es estupendo para entendiendo data, haciendo visualizaciónes, aprendiendo algoritmos, escribiendo ensayos interactivos y más.  Esta platica va a cubrir los basicos de creyendo un cuaderno en la platforma, incluyendo ejercicios que los asistentes pueden seguir en vivo con tus telefonos o laptops.

## Outline

1. Por que ObservableHQ
2. Ejemplos
    1. [Sonidos](https://observablehq.com/@freedmand/sounds?collection=@observablehq/explorables)
    2. [Arte](https://observablehq.com/@mootari/getting-artsy-with-lloyd?collection=@observablehq/generative-art)
    3. [Astronomia](https://observablehq.com/@pcarleton/equinox-is-a-lie-kind-of)
    4. [Ciencia](https://observablehq.com/@kristw/boba-science?collection=@observablehq/explorables)
3. Tutorial
    1. “Cells”
    2. Deslizadores
    3. Las dependencias en otros cuadernos
    4. Visualizacion de data

```yaml
name: Paul Carleton
url: https://twitter.com/paulcarletonjr
pic: https://pcarleton.com/content/images/2018/06/imageedit_1_6032283030.gif
bio: "Desarollador en Stripe, novato por vida"
```
