### ISSUE TITLE
Cómo construir mejor código en Programación Orientada a Objetos. 

### ISSUE THREAD

**Issue by HeberGB** [javascriptmx/chelajs#152]
### Título 
Cómo construir mejor código en Programación Orientada a Objetos (SOLID & design patterns) 

### Sumario

Tener mejores prácticas al programar con el paradigma OO es más fácil con SOLID y patrones de diseño. 

### Outline

1. SOLID 
1.1. ¿Qué es? 
1.1.1. S - Single-responsiblity principle
1.1. 2. O - Open-closed principle
1.1.3. L - Liskov substitution principle
1.1.4. I - Interface segregation principle
1.1.5. D - Dependency Inversion Principle

2. Design Patterns 
2.1. ¿Qué son? 
2.2. Los más comunes
2.2.1. Singleton
2.2.2. Factory
2.2.3. Strategy
2.2.4. Observer
2.2.5. Builder
2.2.6. Adapter
2.2.7. State

3. Conclusiones 
3.1. Ventajas y desventajas 
3.2. Casos de uso 

```yaml
name: Heber Grajeda 
url: https://twitter.com/hebergb
pic: https://pbs.twimg.com/profile_images/947324904604549120/9oIa-T8K.jpg
bio: "Fullstack developer, entusiasta de Node.js, fan de docker"
```
