### ISSUE TITLE
Pruebas o el arte de lavarte las manos

### ISSUE THREAD

**Issue by sanjorgek** [javascriptmx/chelajs#153]
### Sumario

Hablaré desde lo importante de hacer pruebas, lo importante de definir un nivel de pruebas, mínimo de pruebas aceptables, escoger las mejores herramientas hasta el cómo ir al siguiente nivel en pruebas

### Outline

1. Introducción
    - importancia
    - mi experiencia
2. Identificar pruebas
    - campos semánticos
    - tipos y niveles
    - DDT vs TDD
3. Herramientas
    - mocha.js
    - lab.js
    - jest
    - otros
    - consejos
4. Temas avanzados
    - pruebas formales
    - pruebas de mutación
    - pruebas mínimas completas y correctas
5. Recomendaciones
6. El futuro de las pruebas

```yaml
name: Jorge Santiago Alvarez Cuadros
url: https://gitlab.com/sanjorgek
pic: https://avatars3.githubusercontent.com/u/6834622?s=400&v=4
bio: "Programmer, Architect, Scientist, Adviser, Pokemon trainer, Haskell Ninja, Romantic"
```
