### ISSUE TITLE
Moleculer Framework

### ISSUE THREAD

**Issue by sanjorgek** [javascriptmx/chelajs#154]
### Sumario

Hablaré sobre el framework para microservicios [Moleculer](https://moleculer.services/) que presenta muy buenas caracteristicas en su versión beta.

### Outline

1. Introducción
    - Que son los microservicios
    - Ventajas
2. Moleculer
    - Filosofía
    - Arquitecturas
    - Brokers
    - Pruebas
3. Ejemplo

```yaml
name: Jorge Santiago Alvarez Cuadros
url: https://gitlab.com/sanjorgek
pic: https://avatars3.githubusercontent.com/u/6834622?s=400&v=4
bio: "Programmer, Architect, Scientist, Adviser, Pokemon trainer, Haskell Ninja, Romantic"
```
