### ISSUE TITLE
Cosas que me hubiera gustado saber cuando comencé mi carrera como ingeniero de software

### ISSUE THREAD

**Issue by Sparragus** [javascriptmx/chelajs#155]
Esta plática es una lista de consejo de cosas que me hubiera gustado saber cuando comencé mi carrera como ingeniero de software. No podré contarles todo, pero si algunos 5-10 consejos.

Ejemplos:
1. No trabajar solo
2. Evitar la sobre ingeniería
3. Evitar la fatiga de información

Me gustaría presentar en noviembre. Es el único mes que voy a poder. Después de eso no estaré más en México hasta no se cuando.

```yaml
name: Richard B. Kaufman López
url: https://twitter.com/sparragus
pic: https://pbs.twimg.com/profile_images/1094796367384334337/nqikOZ_d_400x400.jpg
bio: "Ingeniero de software y educador."
```
