### ISSUE TITLE
Frontend testing y cómo empezar

### ISSUE THREAD

**Issue by aegre** [javascriptmx/chelajs#156]
### Sumario

Hablaré sobre pruebas en el frontend, mi experiencia en cómo comencé, algunos tips y recomendaciones. Se que se habla mucho sobre pruebas, pero a veces en el frontend son algo ignoradas. Esta charla más que técnica, busco darle una perspectiva más personal.

### Outline

# Pending Title

## Introducción

- View general sobre el testing en frontend, es un mundo oscuro? Son datos pero estos tienen estructura y se ven en el navegador WTF

## Por qué es difícil probar?

- Falta de interés
- Desconocimiento (Es doloroso cuando estás comenzando)
- Presión/Tiempo
- Flojera

## Cómo y qué probar?

- Prueba interacción
- Componentes/Funciones unitarias
- Manten un balance en el punto anterior

## Y yo qué gano?

- Reduce errores
- Refactor son más sencillos
- Te hace mejor desarrollador :)

## Consejos

- Iniciar con flujos completos 
- Analiza qué y cómo probar?
- No te fíes del coverage

## Herramientas (Mis favoritas)

- Jest + Jest-DOM =  ❤️

```yaml
name: Michell Alegría
url: https://twitter.com/aegre
pic: https://pbs.twimg.com/profile_images/845026314549575680/wgHOGEnN_400x400.jpg
bio: "Frontend engineer"
```
