### ISSUE TITLE
Tips para mejorar la cultura de desarrollo en el code review

### ISSUE THREAD

**Issue by paulasaguz** [javascriptmx/chelajs#157]
### Sumario
Hola! me gustaría hacer una charla acerca de cómo podemos mejorar nuestra cultura haciendo code review, este es un proceso en el que colaborativamente deberían participar todos los miembros del equipo desarrollo, (sin importar su nivel junior o senior) ya que es allí donde precisamos que codigo es el que veremos en nuestra app de aquí a unos buenos meses o años.

Y para fortalecer una metodología eficiente podemos hacer uso de tips de gran valor desde cómo ser abiertos a la crítica, hacer critica de manera divertida y amable con nuestros compañeros, herramientas para hacer visibles los PRs abiertos en github, algunas métricas como las de code climate, el uso de circles CI (u otras herramientas) para garantizar que nuestros test no fallen entre algunas de sus ventajas.
 
### Outline

1. Breve presentacion quien soy 
2. que es hacer code review, que no es y por qué es importante en nuestro equipo
3. algunas experiencias y evolución del code review en mi equipo de trabajo
4. algunos tips que hemos aprendido e implementado
ej. cómo afrontar la crítica de tu propio código, como dar critica al equipo, como hacemos que sea entendible para todos e incluso divertido, y hábitos que el equipo debe construir para lograrlo.
5. herramientas que facilitan el proceso
6. métricas importantes para aprobar un pull request
7. conclusiones

```yaml
name: Paula Johana Sanchez
url: paulasaguz.github.io/Portafolio
bio: "Soy Paula, ingeniera en mecatrónica y actualmente desarrolladora frontend en Runa hr, muy fan de javascript y react librería con la que trabajo a diario, también empleo redux, observables, form y un poco de ruby on rails del lado de back(cuando me veo forzada jeje), en mis ratos libres, mejoro mis skills como dev, colaboró en la escuela de js de platzi como mentora, también entreno karate o disfruto ver peliculas con mi gata perezosa La Tata"
```
