### ISSUE TITLE
Aprendizajes de una adquisición: un año después

### ISSUE THREAD

**Issue by julsgud** [javascriptmx/chelajs#158]
### Lecciones de una adquisición: un año después

Después de ocho meses trabajando en [Noteninja](https://www.noteninja.com/), una pequeña startup de habilitación de ventas, fuimos adquiridos por [Salesloft](https://salesloft.com/) una startup de la misma industria con 3 seed rounds y +$50m de ARR. En ésta plática les quiero contar un poco sobre lo que significa trabajar para startups de ambos tamaños y las mejores lecciones técnicas que encontré como líder de integración del front end de estas dos apps.

### Outline

1. De una startup de 5 personas a una de 250+ en un mes
  - Como es trabajar para una startup pequeña?
  - Como es trabajar para una startup grande?
  - Lo que el desarrollador quiere VS lo que el negocio necesita

2. Lecciones de React más importantes
  - Separación de intereses FTW! 
  - Unit testing de abajo hacia arriba

3. Lecciones de GraphQL mas importantes
  - Pide solo lo que necesitas
  - Apollo cache FTW!
  - Cual es la salud de tu API?

```yaml
name: Julio Gudino
url: https://www.linkedin.com/in/julio-gudino-463794137
pic: https://avatars2.githubusercontent.com/u/12491708?s=460&v=4
bio: "Creativo en software"
```
