### ISSUE TITLE
8 Hacks de Finanzas para Desarrolladores y Freelancers

### ISSUE THREAD

**Issue by AmandaJLA** [javascriptmx/chelajs#159]
### Sumario

Cuando pones el precio de tu trabajo, contemplas el tiempo que requiere? Cuánto gastaste en subscripciones, transporte, etc. para acabar el proyecto? Cómo divides los gastos (e ingresos) con tu equipo? En esta plática, buscamos ayudarles contemplar cómo pensar en tu trabajo como una empresa y cómo profesionalizar tu chamba como freelancer para ganar más y cuidar sus finanzas. 

### Outline

1. Retos financieros para desarrolladores ([soy una empresa!](https://www.dopl3r.com/memes/graciosos/en-junta-conmigo-misma-para-ver-que-pedo/744713))
  - Desarrolladores de Oyster presentan sus experiencias 
2. Los hacks (podemos votar, solo platicar de unos 3 de los tips de abajo) 
  - A llenar el cochinito (cuánto ahorrar) 
  - Cada cosa en su lugar (separar finanzas personales con profesionales) 
  - Ponle signo de pesos (pricing) 
  - Clientes de cinco estrellas (contempla ingresos v. costos en licencias, transporte, etc. para entregar el producto)
  - Zapatera, a tus zapatos (delega con contadores y otros profesionales) 
  - El que la debe, la paga (solo trabaja con contratos para que te paguen)
  - Piensa en el futuro (afores y ahorros a largo plazo) 
  - ¿Deber o no deber? (cuida no sobreendeudarte)
3. Resumen de tips y Q&A
  
Me gustaría presentar el miércoles 4 de diciembre. 

```yaml
name: Amanda Jacobson y el equipo Oyster Financial
url: bit.ly/Oysterio https://www.linkedin.com/in/amjacobson/
pic: https://drive.google.com/a/oyster.io/file/d/1mKRBCy_1cTShGX7LTKIbpRIKWwMh3m6M/view?usp=sharing
bio: "Amanda de dedica a brindar emprendedores con las herramientas que necesitan para crecer y lograr tener el impacto que se busca."
```
