### ISSUE TITLE
Deja de quemar el dinero de tus usuarios 🔥💸

### ISSUE THREAD

**Issue by cesargdm** [javascriptmx/chelajs#160]
**Deja de quemar el dinero de tus usuarios 🔥💸** 

### Sumario

Estás quemando dinero de tus usuarios y a Slim le gusta eso... Veamos qué podemos hacer para que tus usuarios dejen de descargar tantos KB innecesarios y no se les acabe el saldo.

### Outline

1. ¿Cómo es que estás quemando dinero de tus usuarios?
2. ¿Qué se puede optimizar?
  - Imágenes / video
  - Código
  - Transferencia
3. Técnicas de optimización
  - Minify everything
  - Smart Caching y policies
  - Code-splitting
  - When to use Gatsby, SSR or PWA

```yaml
name: César Guadarrama Cantú
url: https://twitter.com/cesargdm
pic: https://pbs.twimg.com/profile_images/1181546072767897600/aAO1Iw8k_400x400.jpg
bio: "Developer, photographer, runner, pseudo-designer and engineer. Born in the best place in the planet (México). Making the world a better place to live since 1996"
```
