### ISSUE TITLE
Monorepo: React Web & React Native

### ISSUE THREAD

**Issue by euzharkov** [javascriptmx/chelajs#161]
### Sumario

_The talk is in English_. There are cases when product has a lot of business logic and want's to share it across web and mobile platforms, especially when the web part uses React and mobile - React Native. Sharable code adds development speed, simplified communication between teams, removes behaviour differences between web and mobile. At the same time there are a lot of things which can increase a solution complexity and add some limits to the final product.

### Outline

1. Project development stages
2. People/teams bottlenecks
3. Technical challenges:
   - npm
   - Metro bundler
4. Dependencies management:
   - Yarn
   - Lerna
5. Platform specific code
6. Platforms UI behavior

```yaml
name: Eugene Zharkov
url: https://twitter.com/2j2e
pic: https://avatars1.githubusercontent.com/u/1824387
bio: "React Native Developer"
```

#### Cuándo

March
