### ISSUE TITLE
¿Qué es Svelte.js?

### ISSUE THREAD

**Issue by gndx** [javascriptmx/chelajs#162]
### Sumario

Svelte un nuevo framework de JavaScript que nos permite construir interfaces de usuario. Es considerado el nuevo competidor en la batalla de los frontends donde compiten React, Angular o Vue.  

Svelte ha cambiado la forma en que trabajan los frameworks o librerías populares del momento, Svelte se ejecuta en tiempo de compilación convirtiendo sus componentes en código imperativo altamente eficiente.

### Outline

1. ¿Qué es Svelte.js?
  - Escribe menos código
  - Adios Virtual DOM
  - Verdaderamente Reactivo
2. ¿Por qué es popular?
  - Nuevo Paradigma
  - Comunidad
  - Ventajas y desventajas
3. ¿Cómo Empezar en Svelte.js?
  - QuickStart (Live Demo)
4. Misceláneo
- Sapper

```yaml
name: Oscar Barajas
url: https://twitter.com/gndx
pic: https://arepa.s3.amazonaws.com/oscar-barajas.png
bio: "Frontend & Foundation Layer at @platzi #master - Lead at Developer Circles from Facebook, ReactJS, Speaker & Blogger. I teach ReactJS in @platzi"
```
