### ISSUE TITLE
Construyendo Performant React Apps en la web

### ISSUE THREAD

**Issue by ivandevp** [javascriptmx/chelajs#164]
### Sumario

La web es un entorno que ha cambiado mucho con el paso del tiempo. Antes uno se preocupaba por optimizar imágenes, fuentes, assets, caching, entre otros. Hoy en día, nos preocupamos por entender cómo funciona una librería y/o framework parar construir aplicaciones y asumimos que en la fase de construcción del proyecto, muchos de estos aspectos de performance estarán resueltos por defecto.

React es una librería para construir interfaces de usuario y aunado a otras librerías, herramientas y principios crean todo un ecosistema que ha cambiado la forma de construir aplicaciones web pero agrega su propia complejidad que hace que nuestro enfoque de performance cuente con más factores a tomar en consideración.

### Outline

1. ¿Qué es performance?
  - Tiempo de carga de página
  - Experiencia de usuario
  - Accesibilidad
2. ¿Qué cosas pueden afectar la carga de una página?
  - Tamaño de recursos
  - Transmisión de datos sobre HTTP
  - Browser rendering
3. ¿Qué cambia en una aplicación de React?
  - Control del rendering
  - Manejo de estado
  - Carga de componentes
4. Ejemplos
  - Casos comunes
  - Herramientas para detectarlas
  - Prácticas para solucionarlos
5. Conclusiones y recomendaciones

```yaml
name: Ivan Medina
url: https://twitter.com/ivandevp
pic: https://avatars1.githubusercontent.com/u/9284690?s=400&v=4
bio: "JavaScript Engineer. Creator of Unexpected News Podcast. Former Google Engineer. Learner from OSS."
```
