### ISSUE TITLE
Nextjs'ing your way to production

### ISSUE THREAD

**Issue by mgranados** [javascriptmx/chelajs#165]
### Sumario

Me gustaría compartir mi experiencia con Next.js 9.2 para crear una plataforma completa (no tan compleja) para compartir reviews de libros. Backend y frontend fueron creados en el framework. Usé mongoDB para guardar datos y le hice deploy a `Now` también hecho por `Zeit`. Me gustaría compartir la experiencia, lo bueno y lo malo que vi.

### Outline

1. Next.js 9.2
  - La experiencia con NextJs para front `/pages`
  - La experiencia con NextJs para back `/pages/api`
  - Review de mi código
2. Lo bueno
  - El routing
  - El api
3. Lo increíble
  - Los middlewares ya disponibles
  - El deploy
  - Mejor que CRA(?)
4. Lo no tan bueno
  - Los middlewares limitados
  - Las envs al hacer deploy
  - Logs en Now limitados
5. El Deploy!
  - Deploys a Now 
  - Serveless functions
6. Demo
  - Probamos booktalk.io

```yaml
name: Martín Granados García
url: https://twitter.com/martingranadosg
pic: https://pbs.twimg.com/profile_images/679501416843481088/J_5a5w1L_400x400.jpg
bio: "Frontend Engineer. hacker/painter"
```
