### ISSUE TITLE
Design systems con Storybook

### ISSUE THREAD

**Issue by lehiart** [javascriptmx/chelajs#166]
### Sumario

Hablaré sobre Design systems para aplicaciones en javascript, por qué es importante, que ventajas y desventajas da, así como multiples herramientas para implementarlo en nuestro proyecto.

Usare Storybook implementado en React como herramienta principal, pero los conceptos aplican a cualquier framework o JS puro.

### Outline

1. Introducción
  - ¿Que es?. De donde surgió la idea.
  - ¿Realmente lo necesito?
  
2. Conceptos generales 
  - Arquitectura
  - Herramientas
 - Test

3. Implementacion
  - Pros y contras
  - Como implementarlo en mi codebase
  - Pensando a futuro y conclusion.

```yaml
name: Lehi Arteaga
url: https://twitter.com/lehiart
pic: https://pbs.twimg.com/profile_images/1095823386343698432/QJ1dXS8U_400x400.png
bio: "UI Engineer @ Nubank"
```
