### ISSUE TITLE
Gihub actions

### ISSUE THREAD

**Issue by Ikana** [javascriptmx/chelajs#167]
1. CI/CD con GitHub actions
2. Hablare de como usar GitHub actions para construir correct tu pipeline de continuos delivery 
3. Hablare primero de la sintaxis de actions y luego un ejemplo practico
4. Rodrigo es ingeniero de infraestructura en NYC
4. Por video llamada porque corona virus

```yaml
name: Rodrigo Quezada
url: https://twitter.com/rodikana
pic:https://pbs.twimg.com/profile_images/1032368657035223040/LEWANQkj_400x400.jpg
bio: "Sobreviviendo el Corona en el mero epicentro"
```
