### ISSUE TITLE
Sanity, un CMS en esteroides 💪🏼

### ISSUE THREAD

**Issue by cesargdm** [javascriptmx/chelajs#168]
### Sumario

Hablaré sobre Sanity un CMS que te ofrece mucho más de lo que estamos acostumbrados; hablaré del proyecto que estoy trabajando con Sanity, una serie de landing pages que están siendo alimentadas por Sanity y provee de una enorme posibilidad de estructurar contenido de muchas maneras

Showcase de:
https://jv.cesargdm.now.sh/platea/
https://jv.cesargdm.now.sh/lexum/
https://jv.cesargdm.now.sh/calatea/

A presentar el 6 de mayo 2020

### Outline
  - Que es un CMS, y por qué no son muy útiles
  - Sanity 🤩
  - Mi primer proyecto con Sanity (y seguramente no el último)
  - Arte con Sanity/Live demo 🤞🏽

```yaml
name: César Guadarrama Cantú
url: https://cesargdm.com
pic: https://pbs.twimg.com/profile_images/1181546072767897600/aAO1Iw8k_400x400.jpg
bio: "Developer, photographer, runner, pseudo-designer and engineer. Born in the best place in the planet (México). Making the world a better place to live since 1996"
```
