### ISSUE TITLE
Infraestructura cómo código con Pulumi

### ISSUE THREAD

**Issue by Carlangueitor** [javascriptmx/chelajs#169]
### Sumario

Pulumi es una herramienta para representar infraestructura, principalmente cloud, cómo código; es diferente de otras herramientas ya que ésta usa leguajes de verdad cómo Typescript o Python en lugar de lenguajes de configuración especificos o YAML/JSON dando una mayor control y flexibilidad.

### Outline

- Intro a la IaC
- Pulumi
- Demo

```yaml
name: Charly Román
url: https://twitter.com/eventloopmx
pic: https://s.gravatar.com/avatar/6b41a983c01d3af0ca1c8f51eab96a48?s=80
bio: SRE @ Capital
```
