### ISSUE TITLE
Presentando Café con Ingenieras

### ISSUE THREAD

**Issue by SusCasasola** [javascriptmx/chelajs#170]
### Sumario

Hablaré sobre una iniciativa que hice junto con una amiga para conocer a más mujeres ingenieras.

### Outline

1. ¿Qué es Café con Ingenieras?
2. ¿Cuál es el objetivo principal?
3. ¿Cuántas personas han estado involucradas?
4. ¿Qué temas hemos discutido?
5. ¿Cuáles son los planes a futuro?

```yaml
name: Susana Casasola
url: https://twitter.com/SusCasasola
pic: https://pbs.twimg.com/profile_images/1285828297805508611/5L3iJ-BN_400x400.jpg
bio: "Hola! soy Frontend Engineer de la CDMX, actualmente trabajando en Nubank."
```
