### ISSUE TITLE
WTF hay un poco de React en mi terminal.

### ISSUE THREAD

**Issue by aegre** [javascriptmx/chelajs#172]
### Sumario

Hablaré sobre la librería ink, un proyecto que acabo de descubrir pero se me hace muy interesante.

### Outline

1. Qué es ink?
2. Algunos ejemplos
3. Let's try it! (Necesito consejo acá, mi idea es programar algo sencillo, creo que es más fácil ver código en el stream por lo que no lo veo tan descabellado)

```yaml
name: Michell Alegría
url: https://twitter.com/aegre
pic: https://pbs.twimg.com/profile_images/845026314549575680/wgHOGEnN_400x400.jpg
bio: "Just another boring frontend developer"
```
