### ISSUE TITLE
Trabajando con deuda técnica en una startup

### ISSUE THREAD

**Issue by jmz7v** [javascriptmx/chelajs#173]
### Sumario

Por casi un año estuve trabajando en quitar una gran parte de la deuda técnica en nuestra aplicación, éstas son las cosas que aprendí tratando de balancear arreglar nuestros problemas y seguir construyendo nuevas cosas.

### Outline

A principios de año estábamos batallando mucho usando GraphQL con nuestra app de front-end, nos costaba tiempo de desarrollo, nuestro setup era frágil. Decidimos preguntarnos lo siguiente:
  - ¿Cuál es el costo actual de usar GraphQL en nuestra situación?
  - ¿Cuáles son las alternativas que tenemos?
  - Tomar la decisión de seguir o abandonar (decidimos abandonar GraphQL)

Ahora que decidimos dejarlo, necesitamos un plan de migración:
  - ¿Qué cosas son críticas y no se pueden romper?
  - ¿Cómo saber qué orden poder seguir?
  - ¿Cuáles son los blockers que tenemos?

Ejecutando el plan
  - Planear tiempo para hacer refactor (repot 👀)
  - Balancear nuevos features vs actualizar features existentes o quitar features
  - Tener testing estable (unit, static, end-to-end)

Conclusiones
- Lecciones aprendidas
- Cosas que pudimos hacer distinto
- Beneficios después de la migración

### Acerca de mí

```yaml
name: Julio Montaño
url: https://jmz7v.com/blog
pic: https://jmz7v.com/about/oaxaca.jpg
bio: "Escribo código y propongo cosas en Capital Technologies"
```
