### ISSUE TITLE
Entendiendo Redux con redux-toolkit

### ISSUE THREAD

**Issue by nacho-sg** [javascriptmx/chelajs#174]
1. El **título** de este issue debe ser el título de tu charla,
2. Un breve sumario (par de oraciones) que describan de que se trata
3. El outline que seguirás,
4. Tu "adword", y opcionalmente
4. Cuándo te gustaría presentar

Redux es una herramienta que implementa el patron Flux que ha sido satanizado por la falta de entendimiento, lo que hace que algunos desarrolladores no quieran utilizarlo porque en su experiencia no ha sido un buen approach a su proyecto.

- ¿Cómo?
Haremos una presentacion técnica, seguida de un live coding de como manejar y ver la facilidad de setup que nos ofrece redux-toolkit.

Me gustaria presentar en diciembre

```yaml
name: ignacio sainz guerra
url: https://www.linkedin.com/in/ignacio-sainz-67981115b/
pic: https://media-exp1.licdn.com/dms/image/C4E03AQHNXaX_KC9z1g/profile-displayphoto-shrink_100_100/0?e=1609372800&v=beta&t=5geixzeF2n9jkHlHBs-gUlmipaoEDfBAgFryL-VAe-c
bio: Javascript developer con la meta de entender como funciona todas las herramientas que uso.
```
