### ISSUE TITLE
@adeira/sx: atomic CSS-in-JS inspired by StyleX by Facebook

### ISSUE THREAD

**Issue by mrtnzlml** [javascriptmx/chelajs#175]
Hello Eventloop! 👋 

### Sumario

I'd like to introduce [@adeira/sx](https://github.com/adeira/sx) which is currently being actively developed. [@adeira/sx](https://github.com/adeira/sx) is an atomic CSS-in-JS solution inspired by StyleX (which is a closed-source project by Facebook) and React Native stylesheets. [@adeira/sx](https://github.com/adeira/sx) is focused on feature-complete and easy to work with style solution for React applications with atomic CSS output. Let me show you what are we up to and hopefully inspire you to try something new, something out of the box.

### Outline

1. what is atomic CSS and why bother, goals of the project
1. how does StyleX (and OSS version [@adeira/sx](https://github.com/adeira/sx)) solve this problem
1. [@adeira/sx](https://github.com/adeira/sx) features
  a. styles precedence in SX vs. CSS
  b. pseudo CSS classes, `@at` rules (medias, keyframes)
  c. strict Flow types for _every_ CSS property and value
  d. server-side rendering
  e. eslint rules for SX
1. SX Tailwind and future plans
1. call for action

### Bio

```yaml
name: Martin Zlámal
url: https://github.com/mrtnzlml
pic: https://avatars0.githubusercontent.com/u/978368
bio: "Fulltime open-source developer, previously at Kiwi.com and Pipedrive.com"
```

### Cuándo

December, or anytime you have a free slot
