### ISSUE TITLE
Shipit: copy your commits from monorepo to many repositories (and vice versa) flawlessly

### ISSUE THREAD

**Issue by mrtnzlml** [javascriptmx/chelajs#176]
Hello Eventloop! 👋

### Sumario

When I was working in [Kiwi.com](https://www.kiwi.com/mx/), we used to have a private GitLab (mono)repository. But we **loved** open source! So we built [Shipit](https://github.com/adeira/shipit) to help us export and import our projects flawlessly. Shipit is not just a stupid exporter though! It can export (and import) repositories in a completely different shape which is more suitable for open source. It can even modify the source code or remove unwanted files. 🤯 I will show you how does it work behind the scenes and explain the unexplored possibilities Shipit has.

### Outline

1. history of Shipit and why we built it
1. how are we using it today (and how could you)
1. basic workflow (monorepo 👉 many repositories)
1. more complex workflow (monorepo 👉 monorepo, paths mapping, source code modifications)
1. Importit! (Shipit in reverse)
1. call for action

### Bio

```yaml
name: Martin Zlámal
url: https://github.com/mrtnzlml
pic: https://avatars0.githubusercontent.com/u/978368
bio: "Fulltime open-source developer, previously at Kiwi.com and Pipedrive.com"
```

### Cuándo

anytime you have a free slot
