### ISSUE TITLE
Gulp, sass , jade , livereload ...

### ISSUE THREAD

**Issue by Ikana** [javascriptmx/chelajs#45]
Hola, me gustaría compartir el workflow que he estado depurando los últimos meses, para obtener feedback y sobretodo para difundir la buena palabra de gulp.

Primero daría un overview de gulp, después ya entraría de lleno a crear tasks y ya mostraria uno de mis gulp files funcionando.

```yaml
name: Rodrigo Quezada
url: https://twitter.com/chela_js
pic: https://pbs.twimg.com/profile_images/704544900990152704/r1XMV2Xv_400x400.jpg
bio: "Tu biografía en una oración"
```

**Comment by unRob** [comment]
Gracias por tu propuesta Rodrigo, nos puedes mostrar un outline de tu plática para agarrarle bien la onda? También, voy a necesitar que nos regales tus datos editando tu post inicial.

**Comment by Ikana** [comment]
Bueno la platica comenzaría como una introducción a los task runners como gulp o grunt y luego alternativas a estos.

Despues ya entraría en un ejemplo de un gulp file que tengo en producción que plugins utilizo como implemente ciertas funcionalidades(livereload,watch,babel) y por ultimo pedir feedback de la comunidad para que sea un poca mas interactivo.

```yaml
name: Rodrigo Quezada
url: https://twitter.com/rodikana
pic: https://en.gravatar.com/userimage/21615064/2a04478fb27406fbb324899e8a8a4bc3.jpg?size=200
bio: "Front end Dev en smartassistant"
```
