### ISSUE TITLE
Desarrollo ágil con NPM y Jade

### ISSUE THREAD

**Issue by gorilonmax** [javascriptmx/chelajs#46]
Hablaré sobre una forma ágil de desarrollar páginas web estáticas usando Jade, sin gran esfuerzo, enfocándose en el contenido. Además, hacer notar que se puede usar NPM como Tasks runner.

```yaml
name: Alberto Mendoza
url: https://twitter.com/gorilonmax
pic: https://pbs.twimg.com/profile_images/2019334272/Avatar.png
bio: "Como desarrollador, amo la prestidigitación en las páginas web ®"
```
