### ISSUE TITLE
Chatops con hubot y rundeck 

### ISSUE THREAD

**Issue by xalakox** [javascriptmx/chelajs#47]
Hablaria sobre cómo lo implementamos en SocialDecode y como aceleramos el tiempo de entrega a usuarios y clientes, así como implementación de scripts de remediación. 

Outline 

- porque y para qué ChatOps
- hubot
- conexión a slack 
- conexión a rundeck
- notificaciones
- remediación usando datadog
- mejores y peores prácticas. 

Lo puedo presentar no en domingo :p 

```yaml
name: Salvador Aceves
url: https://twitter.com/SalvadorAceves
pic: https://pbs.twimg.com/profile_images/709146173777387521/ajlS5yFl_400x400.jpg
bio: "Padre de Familia, Developer y entusiasta de la Guitarra."
```
