### ISSUE TITLE
Echando a perder se aprende

### ISSUE THREAD

**Issue by unRob** [javascriptmx/chelajs#48]
### Sumario

Una guía práctica sobre como cagarla a diario y sentirse orgulloso al respecto, resultado de una ardua investigación conducida por uno de los procrastinadores más descarados que conozco: su servidor.

### Outline

- Parte I: _El que con lobos anda_
    - Vamos por chelas
    - ¡A los internets!
    - Colaborando
- Parte II: _El que no puede, enseña_
    - Conseguir un mentor
    - Aprovecharlo
    - Copiarlo descaradamente
- Parte III: de _Chile, mole, y pozole_
    - _El que a buen árbol se arrima_: de hacer open source
    - _Más sabe el diablo por viejo_: de la historia del software
    - _A la mejor cocinera_: de los fracasos 
- Conclusión
    - Cagarla por _deporte_,
    - o por dinero

```yaml
name: Roberto Hidalgo
url: https://twitter.com/unRob
pic: https://pbs.twimg.com/profile_images/506704191608213504/xGqgBkXL_400x400.jpeg
bio: "Autodidacta salvaje"
```
