### ISSUE TITLE
Introduccion a Nativescript

### ISSUE THREAD

**Issue by kiramishima** [javascriptmx/chelajs#49]
### Sumario

Una pequeña introducción a Nativescript, por que usar Nativescript, como usar Nativescript desde el CLI, y mostrare un pequeño demo desde la nube (ya se no mola, pero mi equipo falla :disappointed:  )

### Outline

1. Presentación
  - De PHP / C# a NodeJS / Go
  - FriendzoneTeam
2. Introducción a Nativescript
  - Que es Nativescript
  - Por que usar Nativescript
  - Como contribuir a Nativescript
3. Requerimientos, Codigo Nativo, Modulos, Nativescript CLI, Features
  - Requerimientos para usar Nativescript
  - Ejemplo de uso del Codigo Nativo de Android e iOS
  - Modulos Everywhere !!!
  - Nativescript CLI y la opción de paga.
  - Babel, Typescript, Angular 2, Golang meets Nativescript
4. Demo
  - Liga de un demo corriendo desde un dispositivo android en la nube.

```yaml
name: Paúl Arizpe
url: https://twitter.com/kiramishima
pic: https://avatars3.githubusercontent.com/u/12620426?v=3&s=460
bio: "Fullstack Developer, Gamer, autodidacta & cambio backends hechos en Java a NodeJS ó Go "
```

Lo puedo presentar entre Mayo y probablemente en el chelajs de junio.
Cuando tenga los slides les mando un DM en el slack.
