### ISSUE TITLE
Immutable.js

### ISSUE THREAD

**Issue by Sparragus** [javascriptmx/chelajs#52]
Estamos buscando un ponente para que dé una plática de este tema.

Presentar una plática en ChelaJS es bien fácil. Necesitamos:

1. El título de tu charla,
2. Un breve sumario (par de oraciones) que describan de que se trata
3. El outline que seguirás,
4. Tu "adword", y opcionalmente
5. Cuándo te gustaría presentar

Si tienes dudas o te gustaría platicar antes de presentar:
  - Échale un ojo al wiki: https://github.com/javascriptmx/chelajs/wiki
  - Checa #chelajs en nuestro canal de slack: https://chat.javascriptmx.com

Usa el 'template' aqui abajo, cópialo, y envía la información como comentario a este issue.

---

### Título

Como dar pláticas en ChelaJS

### Sumario

Hablaré sobre...

### Outline

1. Presentar pláticas es la onda
  - Cuenta una historia
  - Hablanos sobre lo que aprendiste
  - Muestranos tus proyectos
2. Enemigos comunes
  - Código diminuto (36px pa arriba)
  - Demasiado texto (sólo bullets)
3. ¿Cómo le hacemos?
  - Dry runs
  - Estructurando nuestras ideas
  - ??
  - PROFIT!!!1!

### Short Bio/Adword
```yaml
name: Graciela J. Script
url: https://twitter.com/chela_js
pic: https://pbs.twimg.com/profile_images/704544900990152704/r1XMV2Xv_400x400.jpg
bio: "Tu biografía en una oración"
```

### Cuando te gustaría presentar?

En el ChelaJS de julio 2016

**Comment by Ikana** [comment]
Yo puedo tomarla ando migrando un codigo de angular, a react con redux immutable y reselect.

A mi gustaria presantarlo en contexto de react pero podria ser stand alone.

**Comment by Sparragus** [comment]
@Ikana Me parece súper bien que lo presentes dentro de un contexto de React y Redux. Me gustaría que los introduzcas standalone, y el resto de la pres dentro de React.

Quizas sea mejor saltar la parte de reselect. Creo que explicando como immutable ayuda a mantener el store sin ser modificado directamente basta. Pero si crees que aporta mucho, go for it.

Venga. Me gusta mucho el tema. Crees que entonces nos puedas dejar el título, sumario, outline de la plática y tu info/bio en el próximo comment? (Es la info que está en el primer comentario).

**Comment by Sparragus** [comment]
@ikana Se acaba de abrir un espacio de speaker para el 1 de junio. Como lo ves?

**Comment by Ikana** [comment]
### Título

Immutable: como y porque?

### Sumario

Una introduccion a la implementacion de immuatable y como se aplica al mundo real

### Outline

- Que es reTrieve
- Array en Immuatable
- Hash en Immuatable
- Como la immutabilidad simplifica el desarrollo
- Memoization
- shouldComponentUpdate

```yaml
name: Rodrigo Quezada
url: https://twitter.com/rodikana
pic: https://en.gravatar.com/userimage/21615064/2a04478fb27406fbb324899e8a8a4bc3.jpg?size=200
bio: "Desarrollador y bailarin amateur"
```

En el ChelaJS de julio 2016

**Comment by Sparragus** [comment]
Creo que es importante que comiences la plática hablando sobre qué significa que la data sea inmutable vs mutable. Luego puedes hablar sobre como se beneficia y simplica el desarrollo. Y luego introduces la librería, Immutable.js.

Lo que quiero decir es que antes de comenzar a hablar sobre React o Redux, o incluso de Immutable.js tal cual, tienes que comenzar introduciendo el tema. Recuerda que muchas personas nunca han escuchado de esta librería o estos conceptos.

Otras preguntas sobre tu outline:
  1. ¿A qué te refieres con 'retrieve'?
  2. ¿Qué nos quieres decir con shouldComponentUpdate?
  3. Sobre memoization, ¿esto sigue siendo un tema de Immutable.js o de reselect?

¿Crees que nos puedes enviar un outline revisado? Esta vez considera añadir una introducción al tema.

De todas formas, vamos bien :) Podemos seguir trabajando el outline y saldrá una gran presentación.

**Comment by jeduan** [comment]
Agregando a lo que dice Richard, creo que el paso 2 es entender si se puede usar la inmutabilidad con sólo JS y cuál es el problema que resuelve usar una librería y me encanta lo de cómo la inmutabilidad simplifica el desarrollo. Creo que sería de lo primero que haría.

**Comment by jeduan** [comment]
Hola @Ikana. ¿Entonces listo para dar la plática en el evento de Julio?

Es el 6 de Julio en el Centro de Cultura Digital

**Comment by Ikana** [comment]
Si me late, que les parece el outline un poco mas explicado?

### Título

Immutable: como y porque?

### Sumario

Una introduccion a la implementacion de immuatable y como se aplica al mundo real

### Outline

- Immutabilidad con Object.assign()
- Que es reTrieve(una embarradita de como immutable trabaja a bajo nivel)
- Array en Immuatable
- Hash en Immuatable
- Como la immutabilidad simplifica el desarrollo
- Memoization( reselect es una implementacion de memoization)
- Como la immutabilidad puede disminir  el rerender del dom.

```yaml
name: Rodrigo Quezada
url: https://twitter.com/rodikana
pic: https://en.gravatar.com/userimage/21615064/2a04478fb27406fbb324899e8a8a4bc3.jpg?size=200
bio: "Desarrollador y bailarin amateur"
```

En el ChelaJS de julio 2016
