### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by Sparragus** [javascriptmx/chelajs#56]
Estamos buscando un ponente para que dé una plática de este tema.

Presentar una plática en ChelaJS es bien fácil. Necesitamos:

1. El título de tu charla,
2. Un breve sumario (par de oraciones) que describan de que se trata
3. El outline que seguirás,
4. Tu "adword", y opcionalmente
5. Cuándo te gustaría presentar

Si tienes dudas o te gustaría platicar antes de presentar:
  - Échale un ojo al wiki: https://github.com/javascriptmx/chelajs/wiki
  - Checa #chelajs en nuestro canal de slack: https://chat.javascriptmx.com

Usa el 'template' aqui abajo, cópialo, y envía la información como comentario a este issue.

---

### Título

Como dar pláticas en ChelaJS

### Sumario

Hablaré sobre...

### Outline

1. Presentar pláticas es la onda
  - Cuenta una historia
  - Hablanos sobre lo que aprendiste
  - Muestranos tus proyectos
2. Enemigos comunes
  - Código diminuto (36px pa arriba)
  - Demasiado texto (sólo bullets)
3. ¿Cómo le hacemos?
  - Dry runs
  - Estructurando nuestras ideas
  - ??
  - PROFIT!!!1!

### Short Bio/Adword
```yaml
name: Graciela J. Script
url: https://twitter.com/chela_js
pic: https://pbs.twimg.com/profile_images/704544900990152704/r1XMV2Xv_400x400.jpg
bio: "Tu biografía en una oración"
```

### Cuando te gustaría presentar?

En el ChelaJS de julio 2016

**Comment by marulango** [comment]
http://i.giphy.com/mG1M7QlI9nDAk.gif


Para Agosto/Septiembre

**Comment by marulango** [comment]
Agosto it is!

**Comment by marulango** [comment]
### Título
Post CSS: Qué, cómo y cuándo.

### Sumario
Responder las preguntas generales de PostCSS y dar un demo muy sencillo.
### Outline

0. Intro
  - Quién soy
  - Auto-promoción sinvergüenza
  - Anuncios parroquiales (?)

1. Qué
  - …es PostCSS
  - …pretende solucionar PostCSS
  - …beneficios tiene PostCSS

2. Cómo
  - …uso PostCSS
  - …extiendo PostCSS

3. Cuándo
  - …debo usar PostCSS
  - …no debo usar PostCSS

4. DEMO TIME!

5. Gracias y buenas noches.

### Short Bio/Adword
```yaml
name: Maru Lango
url: https://twitter.com/marulango
pic: https://pbs.twimg.com/profile_images/445400536569749504/8vJ-Prbe.png
bio: "Full Stack Designer, Freelance, Women Who Code CDMX, Pokémon Master"
```
