### ISSUE TITLE
Mi diseñador se enfermó, se acerca el deadline y tengo que escribir HTML, ¡Ayuda!

### ISSUE THREAD

**Issue by AldoMX** [javascriptmx/chelajs#62]
### Sumario

Hablaré brevemente sobre motores de templating como <s>[Jade](http://jade-lang.com/)</s> [Pug](https://github.com/pugjs/pug), [HAML](http://haml.info/), [Slim](http://slim-lang.com/) y profundizaré en el plugin para editores [Emmet](http://emmet.io/).

### Outline

1. Introducción
    - ¿Qué tiene de malo HTML?
    - Herramientas de templating
        - HAML, Slim y <s>Jade</s> Pug
    - Plugin para IDEs y Editores
        - Emmet
2. Introducción a Emmet
    - Instalando Emmet... ¿Ya está instalado?, [Avísenme...](https://code.visualstudio.com/docs/languages/html#_emmet-snippets)
    - ¿Trabajas con selectores de CSS? Ya conoces el 80% de Emmet
        - Ejemplos utilizando ese 80%
    - Operadores adicionales
        - Ejemplos utilizando operadores adicionales
    - Emmet dentro de CSS
    - Detrás de cámaras (snippets.json)
3. Editando archivos existentes
    - Acciones
    - Ejemplos de acciones
        - Eliminar tags (HTML)
        - Reemplazar contenido (HTML)
        - Evaluar operaciones matemáticas (CSS)
        - Actualizar propiedades con prefijos (CSS)
4. Ok, está muy padre, pero...
    - Tengo una SPA con Angular
        - Habilitando soporte para angular en emmet.syntaxProfiles
        - Ejemplo con directivas
    - Ya uso un motor de templating
        - Combinando Emmet con HAML, Slim o <s>Jade</s> Pug
        - Filtros de Emmet
5. Conclusión
6. Links y Q&A

### Adword

```yaml
name: Aldo Fregoso
url: https://twitter.com/aldo_mx
pic: https://pbs.twimg.com/profile_images/2340121360/4qcivmg564j08t8lrt7d.jpeg
bio: "Escribo sitios web desde los tiempos de ˂BLINK˃Netscape˂/BLINK˃ contra ˂MARQUEE˃Internet Explorer˂/MARQUEE˃."
```

### Cuándo te gustaría presentar

```javascript
moment().isSameOrBefore('2016-12-31');
```
