### ISSUE TITLE
Profiling y benchmarks

### ISSUE THREAD

**Issue by xiam** [javascriptmx/chelajs#64]
En esta plática conoceremos como evaluar el comportamiento de una aplicación headless, en particular de una corriendo sobre nodejs.

También utilizaremos algunas técnicas y herramientas especiales para localizar cuellos de botella y discutiremos cómo resolverlos.

### Outline

1. Procesos en Linux.
2. Procesos con nodejs.
3. Solución de problemas que requieren profiling.

```yaml
name: Carlos Nieto
url: https://twitter.com/xiam
pic: https://avatars2.githubusercontent.com/u/385670?v=3&s=460
bio: "Director General, Mazing Studio"
```
