### ISSUE TITLE
Funciones en la nube: _una introduccion a AWS Lambda_

### ISSUE THREAD

**Issue by Dudemullet** [javascriptmx/chelajs#65]
### Sumario

Aws lambda ayuda a reducir la carga de tu servidor facilmente distribuyendo esta carga via un simple API. Aparte de tomar una carga de tus servidores, Lambda provee una interfaz entre equipos de Python, Java o Javascript via el aws-sdk.

### Outline

1. Intro
  - Quien soy
  - El mejor de los servicios de AWS (la historia de el AWS summit y como recomendaba lambda)
2. ¿Como funciona?
  - ¿Que es lambda?
  - ¿Cuanto te ahorrara?
  - Como se configura
  - Hello world
3. Como lo utilizamos en Konfio
  - Distribucion de responsabilidades (interaccion con data scientists)
  - Paralelizacion de tareas.
4. Demos
  - Fuentes de informacion

```yaml
name: Pipe Gutierrez
url: https://twitter.com/Dudemullet
pic: https://pbs.twimg.com/profile_images/445275703907319808/b4FqriGZ.jpeg
bio: "Arq. de Konfio.mx previo instructor de makersquare y programador agnostico"
```
